@apiUsers = http://localhost:4000/users
@apiEmployees = http://localhost:4000/employees
@apiProjects = http://localhost:4000/projects
@apiBenefits = http://localhost:4000/benefits
@apiVolDeductions = http://localhost:4000/volDeductions
@apiCreateEmployer =  http://localhost:4000/createEmployer
@apiVerifyUser =  http://localhost:4000/verifyUser
@apiEmployer =  http://localhost:4000/employer
POST {{apiUsers}}
Content-Type: application/json

{
  "Email": "aroaefaefexample.com",
  "Contrasenia": "fdef"
}
###
POST {{apiCreateEmployer}}
Content-Type: application/json

{
  "Cedula" : "8765434", 
  "Nombre" : "prueba", 
  "Apellido1" : "por favor", 
  "Apellido2" : "funcione", 
  "Telefono" : "12345567",
  "Email" : "jklkjhg@qwert.com",
  "Contrasenia": "123445"
}
###
POST {{apiVerifyUser}}
Content-Type: application/json

{
  "Cedula": "121121121",
  "Email": "josefR@example.com"
}
###
GET {{apiEmployer}}
###
GET {{apiUsers}}
###
GET {{apiUsers}}/josefR@example.com
###
GET {{apiEmployees}}
###
GET {{apiProjects}}/josefR@example.com

###
GET  {{apiVolDeductions}}/Radiadores Solceri

###
GET {{apiBenefits}}/Radiadores Solceri

###
POST {{apiBenefits}}
Content-Type: application/json

{
  "Nombre":"Prueba444",
  "NombreProyecto": "Radiadores Solceri",
  "CostoActual": 5000
}